import FileLink from './FileLink';
import { useState } from 'react';
import { useWorkflowStore, releaseNotes, type Recipe } from '../workflow/state';
import { useHarnessStore } from '../harness/state';
import { harness } from '../harness/controller';
import { useAppStore } from '../codex/store';
import { session } from '../codex/session';
import { errorMessage } from '../codex/transport';
import { frameFrom } from '../workflow/visual';
import VisualComparison from './VisualComparison';

export function Recipes({cwd}:{cwd:string}){
 const recipes=useWorkflowStore(s=>s.recipes);const [recipe,setRecipe]=useState<Recipe>({id:'',name:'',instructions:''});const [message,setMessage]=useState('');
 const busy=useAppStore(s=>!!s.activeTurn||s.submissionPending||s.threadLoading||s.connection.state!=='ready');const processing=useHarnessStore(s=>s.busy);
 return <section className="workflow-panel"><p>Save reusable instructions. Edit a recipe before running it in a new conversation or adding it to the queue.</p><div className="recipe-list">{recipes.map(r=><button className="btn" key={r.id} onClick={()=>{setRecipe({...r});setMessage('');}}>{r.name}</button>)}</div>
 <button className="btn btn-ghost" onClick={()=>setRecipe({id:'',name:'',instructions:''})}>New recipe</button>
 <label>Recipe name<input value={recipe.name} onChange={e=>setRecipe({...recipe,name:e.target.value})}/></label><label>Recipe instructions<textarea aria-label="Recipe instructions" rows={8} value={recipe.instructions} onChange={e=>setRecipe({...recipe,instructions:e.target.value})}/></label>
 <div className="workbench-actions"><button className="btn" disabled={!recipe.name.trim()||!recipe.instructions.trim()} onClick={()=>{const saved={...recipe,id:recipe.id||crypto.randomUUID(),name:recipe.name.trim()};useWorkflowStore.setState(s=>({recipes:[...s.recipes.filter(r=>r.id!==saved.id),saved]}));setRecipe(saved);setMessage('Recipe saved.');}}>Save recipe</button>{recipe.id&&<button className="btn btn-ghost" onClick={()=>{useWorkflowStore.setState(s=>({recipes:s.recipes.filter(r=>r.id!==recipe.id)}));setRecipe({id:'',name:'',instructions:''});}}>Delete recipe</button>}
 <button className="btn btn-primary" disabled={busy||processing||!recipe.instructions.trim()} onClick={()=>{setMessage('');void (async()=>{harness.pauseQueue();await session.newThread();await session.send(recipe.instructions);setMessage('Recipe started in a new conversation.');})().catch(e=>setMessage(errorMessage(e)));}}>Run recipe</button>
 <button className="btn" disabled={!recipe.instructions.trim()} onClick={()=>{harness.enqueue(cwd,recipe.instructions);setMessage('Recipe added to the queue.');}}>Queue recipe</button></div><p role="status">{message}</p></section>;
}
export function Timeline({cwd}:{cwd:string}){
 const entries=useWorkflowStore(s=>s.timeline);const checkpoints=useHarnessStore(s=>s.checkpoints[cwd]);const busy=useAppStore(s=>!!s.activeTurn||s.submissionPending||s.threadLoading);const [error,setError]=useState('');
 return <section className="workflow-panel"><p>Task results and recorded checks, newest first. Up to 200 recent tasks are saved locally; visual captures retain the 12 most recent comparisons.</p>{error&&<p role="alert">{error}</p>}{!entries.some(t=>t.cwd===cwd)&&<p>Completed and interrupted tasks will appear here.</p>}{entries.filter(t=>t.cwd===cwd).map(t=><article className="checkpoint-card" key={t.id}><small>{new Date(t.updatedAt).toLocaleString()} · {t.status}</small><p className="workflow-summary">{t.summary}</p><b>File review: {checkpoints?.find(c=>c.id===t.checkpointId)?.status??'not available'}</b><details><summary>{t.changedFiles.length} changed files</summary><ul>{t.changedFiles.map(f=><li key={f}><FileLink cwd={cwd} path={f}><code>{f}</code></FileLink></li>)}</ul></details>{t.remaining.length>0&&<p>Remaining: {t.remaining.join('; ')}</p>}{t.checks?.map((c,i)=><details key={i}><summary>{c.command} · exit {c.exitCode}</summary><pre>{c.output}</pre></details>)}{t.checkpointId&&<VisualComparison id={t.checkpointId}/>}<button className="btn" disabled={busy} onClick={()=>{const s=useAppStore.getState();s.switchCharacter(s.settings.threadCharacters[t.threadId]??'mommy');void session.openThread(t.threadId).catch(e=>setError(errorMessage(e)));}}>Open conversation</button></article>)}</section>;
}
export function ReleaseAssistant({cwd}:{cwd:string}){
 const w=useWorkflowStore();const checkpoints=useHarnessStore(s=>s.checkpoints[cwd]);const browser=useHarnessStore(s=>s.browser);const [error,setError]=useState('');
 const draft=w.releases[cwd]??{version:'',notes:'',screenshots:[],updatedAt:0};
 const patch=(value:Partial<typeof draft>)=>useWorkflowStore.setState(s=>({releases:{...s.releases,[cwd]:{...(s.releases[cwd]??draft),...value,updatedAt:Date.now()}}}));
 const download=()=>{const body=JSON.stringify({project:cwd,...draft},null,2);const url=URL.createObjectURL(new Blob([body],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`release-${draft.version.replace(/[^a-z0-9._-]/gi,'-')||'draft'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="workflow-panel"><p>Prepare a local release draft from task summaries, file review status, recorded build results, and screenshots. Review and edit it before publishing.</p><label>Release version<input value={draft.version} placeholder="v0.3.0" onChange={e=>patch({version:e.target.value})}/></label><button className="btn" onClick={()=>patch({notes:releaseNotes(cwd,draft.version,w.timeline,Object.fromEntries((checkpoints??[]).map(c=>[c.id,c.status])))})}>{draft.notes?'Regenerate notes from timeline':'Generate release notes'}</button><label>Release notes<textarea aria-label="Release notes" rows={16} value={draft.notes} onChange={e=>patch({notes:e.target.value})}/></label><button className="btn" disabled={browser?.project!==cwd||!browser?.screenshot||draft.screenshots.length>=4} onClick={()=>{setError('');if(browser)void frameFrom(browser).then(frame=>{const latest=useWorkflowStore.getState().releases[cwd]??draft;patch({screenshots:[...latest.screenshots,frame].slice(0,4)});}).catch(e=>setError(errorMessage(e)));}}>Attach current preview</button><p className="hint">Up to four screenshots. Export includes image data and capture times.</p>{draft.screenshots.map((f,i)=><figure key={`${f.at}-${i}`}><img className="release-screenshot" src={f.image} alt={`Release screenshot ${i+1}`}/><figcaption>{f.url} · {new Date(f.at).toLocaleString()}</figcaption><button className="btn btn-ghost" onClick={()=>patch({screenshots:draft.screenshots.filter((_,index)=>index!==i)})}>Remove screenshot {i+1}</button></figure>)}<div className="workbench-actions"><button className="btn btn-primary" disabled={!draft.notes.trim()} onClick={download}>Export release draft</button><button className="btn" disabled={!draft.notes.trim()} onClick={()=>void navigator.clipboard.writeText(draft.notes).then(()=>setError('Release notes copied.')).catch(e=>setError(errorMessage(e)))}>Copy release notes</button></div>{error&&<p role="status">{error}</p>}</section>;
}
